[package]
name = "ovit"
version = "0.1.0"
authors = ["Kepler Sticka-Jones <kepler@stickajones.org>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
nom = "5.0.0"
chrono = "0.4.7"

[build-dependencies]
cc = "1.0"
bindgen = "0.50"